import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "5411 ESTATE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo5411estate.png" type="image/png" />
      </head>
      <body className={`${inter.className} ${styles.pageBackground}`}>
        {children}
      </body>
    </html>
  );
}
